site_name: Cascade
site_url: https://saket.github.io/cascade/
repo_name: cascade
repo_url: https://github.com/saket/cascade
site_description: 'Nested popup menus with smooth height animations for Android'
site_author: Saket Narayan
copyright: 'Copyright &copy; 2020 Saket Narayan'
remote_branch: gh-pages

theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.copy # Show a copy button in code blocks.
    - navigation.instant # Instant loading of pages. Behave like a Single Page Application.
    - toc.integrate

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - toc: # Table of contents.
      permalink: true # Anchor linking with headings.
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - macros # For extra.versions.cascade below.

extra:
  versions:
    cascade: '2.3.0' # Env var for the latest version on maven.

nav:
  - 'Overview': index.md
  - 'Compose UI':
    - 'Overview': compose/index.md
    - 'Navigation': compose/navigation.md
    - 'Theming': compose/theming.md
  - 'Views':
      - 'Overview': views/index.md
      - 'Navigation': views/navigation.md
      - 'Theming': views/theming.md
      - 'Custom layouts': views/custom_layouts.md
